%MACRO EXPRESSION_JUDGE(VARS=,RELS=,VALUES=,NAME=,STR=); *�ú����ɱ��ʽ���Լ��ڱ��ʽΪ��ʱ�������;

	*�������ո�;
	%LET VARS=%SYSFUNC(COMPBL(&VARS));
	%LET RELS=%SYSFUNC(COMPBL(&RELS));
	%LET VALUES=%SYSFUNC(COMPBL(&VALUES));

	*���ɵ�һ�����ʽ;
	%LET NUM=1;
	%LET VAR_EXPRESSION=%SCAN(&VARS,&NUM,"/");
	%LET REL_EXPRESSION=%SCAN(&RELS,&NUM,"/");
	%LET VAL_EXPRESSION=%SCAN(&VALUES,&NUM,"/");
	%LET EXPRESSION=(&VAR_EXPRESSION &REL_EXPRESSION &VAL_EXPRESSION);

	*�����������������DOWHILEѭ������ֹ�ڵ�;
	%LET NUM_OF_VARS=%SYSFUNC(COUNTW(&VARS,"/"));

	*�������־ȷ�������Ƿ���ȷ;
	%PUT &NUM_OF_VARS;
	%PUT &EXPRESSION;

	*������һ�����ʽ������һ�����ʽ����ƴ��;
	%DO %WHILE (&NUM LT &NUM_OF_VARS);

		%LET NUM=%EVAL(&NUM+1);
		%LET VAR_EXPRESSION=%SCAN(&VARS,&NUM,"/");
		%LET REL_EXPRESSION=%SCAN(&RELS,&NUM,"/");
		%LET VAL_EXPRESSION=%SCAN(&VALUES,&NUM,"/");

		%LET EXPRESSION=%SYSFUNC(CATX("AND","&EXPRESSION","(&VAR_EXPRESSION &REL_EXPRESSION &VAL_EXPRESSION)"));
		%let EXPRESSION=%SYSFUNC(COMPRESS(&EXPRESSION,'"'));

		*�������־ȷ�������Ƿ���ȷ;
		%PUT &EXPRESSION;

	%END;

	*���ʽΪ��ʱ�������;
	IF &EXPRESSION THEN DO;
		NAME=VNAME(&NAME);
		LABEL=LABEL(&NAME);			
		QUERY=COMPRESS("&STR");
		ANSWER="";
		OUTPUT;	
	END;

%MEND;


%MACRO QUERY_TIMWINDOW(CATALOG=0,DATA1=,DATA2=,CRFNAME=,OUT=,VAR1=,VAR2=,VARS=,RELS=,VALUES=,NAME=,STR=); *�ú�����ʱ�����ݣ������������ݼ�����ʹ�ú�EXPRESSION_JUDGE��������ı�;

*�ж����ڱ���VAR1�����ͣ���������ں����RESULT1;
DATA INSET_1; 
	SET RAWDATA.&DATA1(OBS=1);
	TYPE_1=VTYPE(&VAR1);
	IF TYPE_1='C' THEN TYPE_1_1=1;
	IF TYPE_1='N' THEN TYPE_1_1=2;
	call symput("RESULT1",TYPE_1_1);
RUN;
%PUT &RESULT1; *�������RESULT1�Ƿ���������;

*�ж����ڱ���VAR2�����ͣ���������ں����RESULT2;
DATA INSET_2;
	SET RAWDATA.&DATA2(OBS=1);
	TYPE_2=VTYPE(&VAR2);
	IF TYPE_2='C' THEN TYPE_2_2=1;
	IF TYPE_2='N' THEN TYPE_2_2=2;
	call symput("RESULT2",TYPE_2_2);
RUN;
%PUT &RESULT2; *�������RESULT2�Ƿ���������;

DATA INSET; *����ʱ�����ݣ������������ݼ�;
	
	IF &CATALOG=0 THEN DO; *����CATALOG��ֵΪ0��Ĭ��ֵ��ʱMERGE BY SUBJECTID STUDENTEVENT;
		MERGE RAWDATA.&DATA1 RAWDATA.&DATA2;
		BY subjectID StudyEvent;
	END;
	IF &CATALOG=1 THEN DO; *����CATALOG��ֵΪ1��Ĭ��ֵ��ʱMERGE BY SUBJECTID;
		MERGE RAWDATA.&DATA1 RAWDATA.&DATA2;
		BY subjectid;
	END;

	IF CMISS(&VAR1.,&VAR2.) NE 0 THEN DELETE;
	IF FIND(&VAR1,"K")^=0 OR FIND(&VAR2,"K")^=0 THEN DELETE;

	IF (&result1=1 AND &result2=1) THEN DO; *��VAR1Ϊ�ַ���VAR2Ϊ�ַ���ʱ��VAR1VAR2��ת������ֵ��;
		DATE1=INPUT(SUBSTR(KCOMPRESS(&VAR1),1,10),YYMMDD10.);
		DATE2=INPUT(SUBSTR(KCOMPRESS(&VAR2),1,10),YYMMDD10.);
		IF CMISS(DATE1,DATE2) NE 0 THEN DELETE;
		FORMAT DATE1 DATE2 YYMMDD10.;
	END;
	IF (&result1=1 AND &result2=2) THEN DO; *��VAR1Ϊ�ַ���VAR2Ϊ��ֵ��ʱ��VAR1ת������ֵ��;
		DATE1=INPUT(SUBSTR(KCOMPRESS(&VAR1),1,10),YYMMDD10.);
		DATE2=&VAR2;
		IF CMISS(DATE1,DATE2) NE 0 THEN DELETE;
		FORMAT DATE1 DATE2 YYMMDD10.;
	END;
	IF (&result1=2 AND &result2=1) THEN DO; *��VAR1Ϊ��ֵ��VAR2Ϊ�ַ���ʱ��VAR2ת������ֵ��;
		DATE1=&VAR1;
		DATE2=INPUT(SUBSTR(KCOMPRESS(&VAR2),1,10),YYMMDD10.);
		IF CMISS(DATE1,DATE2) NE 0 THEN DELETE;
		FORMAT DATE1 DATE2 YYMMDD10.;
	END;

RUN;
	
DATA &OUT; *���ú�EXPRESSION_JUDGE��������ı�;

	LABEL subjectID='�����߱��' StudyEvent='����' CRFNAME='CRF������' ItemGroupRepeatKey='CRF���к�' NAME='����' label='������ǩ' QUERY='��������';
	LENGTH CRFNAME $100 NAME $60 QUERY $1000;
	SET INSET;
	CRFNAME="&CRFNAME";
	%EXPRESSION_JUDGE(VARS=&VARS,RELS=&RELS,VALUES=&VALUES,NAME=&NAME,STR=&STR);
	KEEP siteid subjectid StudyEvent CRFNAME ItemGroupRepeatKey NAME label QUERY VISIT;

RUN;

%MEND;


