%MACRO EXPRESSION_JUDGE(VARS=,RELS=,VALUES=,NAME=,STR=); *该宏生成表达式，以及在表达式为真时输出质疑;

*清除多余空格;
%LET VARS=%SYSFUNC(COMPBL(&VARS));
%LET RELS=%SYSFUNC(COMPBL(&RELS));
%LET VALUES=%SYSFUNC(COMPBL(&VALUES));

*生成第一个表达式;
%LET NUM=1;
%LET VAR_EXPRESSION=%SCAN(&VARS,&NUM,"/");
%LET REL_EXPRESSION=%SCAN(&RELS,&NUM,"/");
%LET VAL_EXPRESSION=%SCAN(&VALUES,&NUM,"/");
%LET EXPRESSION=(&VAR_EXPRESSION &REL_EXPRESSION &VAL_EXPRESSION);

*计算变量数量来决定DOWHILE循环的终止节点;
%LET NUM_OF_VARS=%SYSFUNC(COUNTW(&VARS,"/"));

*输出到日志确认数据是否正确;
%PUT &NUM_OF_VARS;
%PUT &EXPRESSION;

*生成下一个表达式并与上一个表达式进行拼接;
%DO %WHILE (&NUM LT &NUM_OF_VARS);

	%LET NUM=%EVAL(&NUM+1);
	%LET VAR_EXPRESSION=%SCAN(&VARS,&NUM,"/");
	%LET REL_EXPRESSION=%SCAN(&RELS,&NUM,"/");
	%LET VAL_EXPRESSION=%SCAN(&VALUES,&NUM,"/");

	%LET EXPRESSION=%SYSFUNC(CATX("AND","&EXPRESSION","(&VAR_EXPRESSION &REL_EXPRESSION &VAL_EXPRESSION)"));
	%let EXPRESSION=%SYSFUNC(COMPRESS(&EXPRESSION,'"'));

	*输出到日志确认数据是否正确;
	%PUT &EXPRESSION;

%END;

*表达式为真时输出质疑;
IF &EXPRESSION THEN DO;
	NAME=VNAME(&NAME);
	LABEL=LABEL(&NAME);			
	QUERY=COMPRESS("&STR");
	ANSWER="";
	OUTPUT;	
END;

%MEND;
