***关联逻辑库并读取format***;
LIBNAME RAWDATA "E:\SAS_DATA\KH_20230114"; 
OPTIONS FMTSEARCH=(RAWDATA); 
***关联逻辑库并读取format***;

***非条件缺失宏***;

%MACRO UNCONDITIONAL_MISSING(OUT=,DATA=,VARIABLE=);
DATA &OUT;
LENGTH NAME$20. LABEL$20. QUERY$50.;
SET RAWDATA.&DATA;

	IF MISSING(&VARIABLE)=1 THEN DO;
		NAME=VNAME(&VARIABLE);
		LABEL=LABEL(&VARIABLE);
		QUERY="缺失，请补充。";
		OUTPUT;
	END;

KEEP siteid subjectid studyevent visit name query label CRFname ItemGroupRepeatKey;
RUN;

%MEND;

*下列代码使用EXCEL制作，更加便捷;

%MISSING_OUTPUT(OUT=OUT1,DATA=SC,VARIABLE=SUBJINI);
%MISSING_OUTPUT(OUT=OUT2,DATA=SC,VARIABLE=RFICDAT);
%MISSING_OUTPUT(OUT=OUT3,DATA=SC,VARIABLE=RFICHR);
%MISSING_OUTPUT(OUT=OUT4,DATA=SC,VARIABLE=RFICMI);
%MISSING_OUTPUT(OUT=OUT5,DATA=SC,VARIABLE=BRTHDAT);
%MISSING_OUTPUT(OUT=OUT6,DATA=SC,VARIABLE=SEX);
%MISSING_OUTPUT(OUT=OUT7,DATA=SC,VARIABLE=NATION);
%MISSING_OUTPUT(OUT=OUT8,DATA=SC,VARIABLE=HEIGHT);
%MISSING_OUTPUT(OUT=OUT9,DATA=SC,VARIABLE=WEIGHT);
%MISSING_OUTPUT(OUT=OUT10,DATA=SC,VARIABLE=SUBJSOUR);
%MISSING_OUTPUT(OUT=OUT11,DATA=SC,VARIABLE=HOSPID);
%MISSING_OUTPUT(OUT=OUT12,DATA=SC,VARIABLE=AHYN);
%MISSING_OUTPUT(OUT=OUT13,DATA=SC,VARIABLE=DRKYN);
%MISSING_OUTPUT(OUT=OUT14,DATA=SC,VARIABLE=SMKYN);
%MISSING_OUTPUT(OUT=OUT15,DATA=SC,VARIABLE=VISDAT1);
%MISSING_OUTPUT(OUT=OUT16,DATA=MA,VARIABLE=SYMPTOM);
%MISSING_OUTPUT(OUT=OUT17,DATA=MA,VARIABLE=MATYPE);
%MISSING_OUTPUT(OUT=OUT18,DATA=MA,VARIABLE=QSTYPE);
%MISSING_OUTPUT(OUT=OUT19,DATA=MHNY,VARIABLE=MHYN);
%MISSING_OUTPUT(OUT=OUT20,DATA=VSYN,VARIABLE=VSPERF);
%MISSING_OUTPUT(OUT=OUT21,DATA=QS1YN,VARIABLE=QS1PERF);
%MISSING_OUTPUT(OUT=OUT22,DATA=IE,VARIABLE=IORRES1-IORRES5);
%MISSING_OUTPUT(OUT=OUT23,DATA=IE,VARIABLE=EORRES1-EORRES12);
%MISSING_OUTPUT(OUT=OUT24,DATA=IE,VARIABLE=IEYN);
%MISSING_OUTPUT(OUT=OUT25,DATA=DS,VARIABLE=DISCONT);
%MISSING_OUTPUT(OUT=OUT26,DATA=CMNY,VARIABLE=CMYN);
%MISSING_OUTPUT(OUT=OUT27,DATA=AENY,VARIABLE=AEYN);
%MISSING_OUTPUT(OUT=OUT28,DATA=LBYN,VARIABLE=LBPERF);
%MISSING_OUTPUT(OUT=OUT29,DATA=DS1,VARIABLE=DSYN);
%MISSING_OUTPUT(OUT=OUT30,DATA=DS1,VARIABLE=BLINDYN);

*最后合并以上数据集;

DATA MISING_RESULT;
SET OUT1-OUT30;
RUN;

***非条件缺失宏***;

